project:
  type: website

website:
  title: "WRFI Lidar"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: technology.qmd
        text: Tech
      - href: goals.qmd
        text: Goals
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: united
    css: styles.css
    toc: false

editor: visual

