project:
  type: website

website:
  title: "WRFILidar-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: technology.qmd
        text: Tech
      - href: goals.qmd
        text: Goals
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

